set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;

call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Have you had an HIV test in the past 1 week?",'Have you had an HIV test in the past 1 week?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Yes",'Yes','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"No",'No','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, When was the test done?",'When was the test done?','Date','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, What was the result?",'What was the result?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Negative",'Negative','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Positive",'Positive','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Unknown",'Unknown','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Inconclusive",'Inconclusive','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Do you have any heath related problems today?",'Do you have any heath related problems today?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If Yes for health related problems today",'Indicate the problem','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Have you been diagnosed of any chronic illness?",'Have you been diagnosed of any chronic illness?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Hypertension",'Hypertension','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Diabetes",'Diabetes','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"CCF",'CCF','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Liver failure",'Liver failure','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Renal failure",'Renal failure','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Psychosis",'Psychosis','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Epilepsy",'Epilepsy','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Other",'Other','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If other for diagnosed for any clinic illness",'If Other Specify details','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Are you or your partner currently pregnant?",'Are you or your partner currently pregnant?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Don't know","Don't know",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, When was you last normal menstrual period?",'When was you last normal menstrual period?','Date','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Pregnacy test done?",'Pregnacy test done?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Pregnancy test What was the result?",'What was the result?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Are you or partner currently breast feeding?",'Are you or partner currently breast feeding?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Are you or your partner using any contraception?",'Are you or your partner using any contraception?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If Other for Are you or your partner using any contraception?",'If Other Specify details','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Barrier method",'Barrier method','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Implant",'Implant','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Injection",'Injection','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"IUDs",'IUDs','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Pills",'Pills','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Are you taking any drugs or medications?",'Are you taking any drugs or medications?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Anti-hypertensives",'Anti-hypertensives','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Diabetics ",'Diabetics','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Anti-Epleptics",'Anti-Epleptics','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Chemotherapy",'Chemotherapy','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Anti-Asthmatics",'Anti-Asthmatics','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If other for taking any drugs or medications?",'If Other Specify details','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Are you on ARVs?",'Are you on ARVs?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Are you sexually active?",'Are you sexually active?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Are you married or in a stable relationship for the past 6 months and above?",'Are you married or in a stable relationship for the past 6 months and above?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Do you know your partner's HIV status?","Do you know your partner's HIV status?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Is your partner on ART?",'Is your partner on ART?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Do you know your partner's adherence to ART?","Do you know your partner's adherence to ART?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Has your partner had a viral load test done in the last 12 months?",'Has your partner had a viral load test done in the last 12 months?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If yes for partner had a viral load test done in the last 12 months?",'Specifiy Results','Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Do you use condoms every time you have sex with your partner?",'Do you use condoms every time you have sex with your partner?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Have you had any other sexual partners in the last 6 months?",'Have you had any other sexual partners in the last 6 months?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If yes for had any other sexual partners in the last 6 months?",'How many?','Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Do you have more than 1 sexual partner?",'Do you have more than 1 sexual partner?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Do you know your non-regular partner(s) HIV status?",'Do you know your non-regular partner(s) HIV status?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Specify HIV status of partner",'Specify HIV status of partner','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Do you use condoms every time you have sex with your non-regular partner?",'Do you use condoms every time you have sex with your non-regular partner?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Have you been treated for an STI in the last 3 months?",'Have you been treated for an STI in the last 3 months?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Have you exchanged sex for money, goods or services?","Have you exchanged sex for money, goods or services?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Do you have a history of sexual abuse/gender based violence?","Do you have a history of sexual abuse/gender based violence?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Have you used emergency contraception in the last 6 months?","Have you used emergency contraception in the last 6 months?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Have you used PEP in the last 6 months?","Have you used PEP in the last 6 months?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, What was the reason for taking PEP?","What was the reason for taking PEP?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Condom burst with partner of Unknown status","Condom burst with partner of Unknown status",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Condom burst with positive partner","Condom burst with positive partner",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Unprotected sex with partner of unknown status","Unprotected sex with partner of unknown status",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Unprotected sex with positive partner","Unprotected sex with positive partner",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Work related exposure","Work related exposure",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If Other for reason for taking PEP?","If Other Specify details",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Are you single or not in a stable relationship?",'Are you single or not in a stable relationship?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Have you had sexual partner(s) in the last 6 months?",'Have you had sexual partner(s) in the last 6 months?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If Yes, How many?",'How many?','Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Do you use condoms every time you have vaginal or anal sex?",'Do you use condoms every time you have vaginal or anal sex?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Have you had a condom burst in the last 3 month?",'Have you had a condom burst in the last 3 month?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If Yes for condorm burst, How many times?",'How many times?','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, In a Single relationship Have you been treated for an STI in the last 3 months?",'Have you been treated for an STI in the last 3 months?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Females",'Females','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Males",'Males','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Genital Ulcer Disease",'Genital Ulcer Disease','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Vaginal Discharge Syndrome",'Vaginal Discharge Syndrome','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Pelvic Inflamatory Disease",'Pelvic Inflamatory Disease','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Genital Herpes",'Genital Herpes','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Genital warts",'Genital warts','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Urethral Discharge Syndome",'Urethral Discharge Syndome','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If other for Males","If Other for Males, Specify",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If other for Females","If Other for Females, Specify",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Have you had sex whilst indoxicated with alcohol or drugs?",'Have you had sex whilst indoxicated with alcohol or drugs?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Have you or your partner used emergency contraception in the last 6 months?",'Have you or your partner used emergency contraception in the last 6 months?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If Yes for emergency contraception, How many times?",'How many times?','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Single or Stable relationship, Have you used PEP in the last 6 months?",'Have you used PEP in the last 6 months?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Single or Stable relationship, What was the reason for taking PEP?",'What was the reason for taking PEP?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Single or Stable relationship, If Other, Specify","If Other, Specify",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Do you inject drugs?",'Do you inject drugs?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Any signs of primary infection?",'Any signs of primary infection?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If Yes for Any signs of primary infection?",'Specify details','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Fever",'Fever','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Rash",'Rash','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Sore throat",'Sore throat','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Arthralgia",'Arthralgia','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"GUD",'GUD','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If yes for other primary infection",'If Other, Specify','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, What is the client's HIV status today?","What is the client's HIV status today?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Are you ready to start Prep?",'Are you ready to start Prep?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If yes for ready to start Prep?, Specify Reason",'Specify Reason','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Afraid of Side effects",'Afraid of Side effects','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Fear of violence from partner",'Fear of violence from partner','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Don’t want a daily treatment",'Don’t want a daily treatment','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Fear of the perception that I am taking ARVs for treatment",'Fear of the perception that I am taking ARVs for treatment','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, If Other for specify reason for ready to start PrEP","If Other, Specify",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Is the client Eligible to take PrEP?",'Is the client Eligible to take PrEP?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Is the client Eligible to take PrEP?, Males",'Males','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Is the client Eligible to take PrEP?, Females",'Females','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"MSM",'MSM','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"BI-SEXUAL",'BI-SEXUAL','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"IUDs",'IUDs','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"SERO-DISC",'SERO-DISC','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"HRM",'HRM','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Transgender",'Transgender','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"FSW",'FSW','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"TSW",'TSW','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Is the client Eligible to take PrEP?, Males Other","If Other for Males, Specify",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form, Is the client Eligible to take PrEP?, Females Other","If Other for Females, Specify",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Init Form Template",'PrEP Initial','N/A','Misc',true);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Do you have any heath related problems today?",'Do you have any heath related problems today?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Yes for health related problems today",'Indicate the problem','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Are you using any family planning method?",'Are you using any family planning method?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If yes for are you using any family planning method?",'Specify Method','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Other for using any family planning method",'If Other Specify','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Last normal menstrual period?",'Last normal menstrual period?','Date','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Are you breast feeding?",'Are you breast feeding?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Are you using any other medications?",'Are you using any other medications?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Yes for Are you using any other medications?",'Specify medications','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If other for using any other medications",'If Other Specify details','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, How many sexual partners have you had since the last visit?",'How many sexual partners have you had since the last visit?','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Do you know your partner's HIV status?","Do you know your partner's HIV status?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Yes for Do you know your partner's HIV status?","If Yes then specify",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Is your partner on ART?",'Is your partner on ART?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Do you know your partner's viral load?","Do you know your partner's viral load?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Yes for Do you know your partner's viral load",'Indicate value','Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Are you using condoms every time you are having sex?",'Are you using condoms every time you are having sex?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Have you had a condom burst since the last visit?",'Have you had a condom burst since the last visit?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If yes for condom burst since the last visit?",'How many times?','Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Have you been treated for an STI since the last visit?",'Have you been treated for an STI since the last visit?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Treated for STI since last visit Females",'Females','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Treated for STI since last visit Males",'Males','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If other for Treated for STI since last visit Females","If Other for Females, Specify",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If other for Treated for STI since last visit Males","If Other for Males, Specify",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Have you had sex whilst indoxicated with alcohol or drugs?",'Have you had sex whilst indoxicated with alcohol or drugs?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Have you exchanged sex for money, goods or services?","Have you exchanged sex for money, goods or services?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Have you been sexually abused or had gender based violence since the last visit?","Have you been sexually abused or had gender based violence since the last visit?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Have you used emergency contraception since the last visit?",'Have you used emergency contraception since the last visit?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Yes for used emergency contraception since the last visit?","How many times?",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Does the client have any sings of primary infection?",'Does the client have any sings of primary infection?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Yes for client have any sings of primary infection?",'Specify details','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Other for yes for client have any sings of primary infection?",'If Other Specify details','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Are you ready to continue PrEP?",'Are you ready to continue PrEP?','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If No for Are you ready to continue PrEP?",'Specify reason','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Other for No for Are you ready to continue PrEP?",'If Other Specify details','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, What is the client's HIV status today?","What is the client's HIV status today?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, Is the client eligible to continue PrEP?","Is the client eligible to continue PrEP?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Yes for the client eligible to continue PrEP? Males","Males",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Yes for the client eligible to continue PrEP? Females","Females",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Other for client eligible to continue PrEP? Males",'If Other for Males Specify details','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form, If Other for client eligible to continue PrEP? Females",'If Other for Females Specify details','Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Prep Cont Form Template",'PrEP Continuation','N/A','Misc',true);
