set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;


call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"VAWG",'VAWG','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"STI",'STI','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for HIV Self Testing",'Provider name for HIV Self Testing','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Provider Testing and Counseling",'Provider name for Provider Testing and Counseling','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Confirmatory HIV testing and Counseling",'Provider name for Confirmatory HIV testing and Counseling','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Contact Tracing",'Provider name for Contact Tracing','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Viac Initial",'Provider name for Viac Initial','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Viac Continuation",'Provider name for Viac Continuation','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for VMMC",'Provider name for VMMC','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for FP Initial",'Provider name for FP Initial','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for FP Counselling Only",'Provider name for FP Counselling Only','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for FP Continuation",'Provider name for FP Continuation','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for VAWG",'Provider name for VAWG','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for STI",'Provider name for STI','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Sylvia Madakadze",'Sylvia Madakadze','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Gurura Blessing",'Gurura Blessing','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Naome Gororo",'Naome Gororo','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Sibanda Lihle",'Sibanda Lihle','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Chawasema Nicholas",'Chawasema Nicholas','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Muchongwe Felix",'Muchongwe Felix','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Geza Tafadzwa",'Geza Tafadzwa','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Kandemiri Helen",'Kandemiri Helen','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Kwedza Zvidzai",'Kwedza Zvidzai','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Murimi Pauline",'Murimi Pauline','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Musinake Charity",'Musinake Charity','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Musonza Diana",'Musonza Diana','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Noko Kudzai",'Noko Kudzai','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Simbanegavi Miriam",'Simbanegavi Miriam','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Chinake Obey",'Chinake Obey','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Choga Ivy",'Choga Ivy','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Cynthia Magwaza",'Cynthia Magwaza','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Chisango Samuel",'Chisango Samuel','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Kamwanza Collen",'Kamwanza Collen','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Mubayiwa Vimbai",'Mubayiwa Vimbai','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Muzunze Blandina",'Muzunze Blandina','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Ngano Thomas",'Ngano Thomas','N/A','Misc',false);
