set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;


call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"VAWG",'VAWG','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"STI",'STI','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for HIV Self Testing",'Provider name for HIV Self Testing','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Provider Testing and Counseling",'Provider name for Provider Testing and Counseling','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Confirmatory HIV testing and Counseling",'Provider name for Confirmatory HIV testing and Counseling','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Contact Tracing",'Provider name for Contact Tracing','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Viac Initial",'Provider name for Viac Initial','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Viac Continuation",'Provider name for Viac Continuation','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for VMMC",'Provider name for VMMC','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for FP Initial",'Provider name for FP Initial','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for FP Counselling Only",'Provider name for FP Counselling Only','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for FP Continuation",'Provider name for FP Continuation','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for VAWG",'Provider name for VAWG','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for STI",'Provider name for STI','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Evelyn Mugwagwa",'Evelyn Mugwagwa','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Joina Asefa",'Joina Asefa','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Jivas Zufuke",'Jivas Zufuke','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Admire Mupazviribwo",'Admire Mupazviribwo','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Wilfred Chinengundu",'Wilfred Chinengundu','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Samuel Mafa",'Samuel Mafa','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Jane Mangwiro",'Jane Mangwiro','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Loice Ncube",'Loice Ncube','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Mary Mujayi",'Mary Mujayi','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Kundai Nyanyiwa",'Kundai Nyanyiwa','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Ennie Chipungu",'Ennie Chipungu','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Kudzai Kwembeya",'Kudzai Kwembeya','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Mercy Chikurira",'Mercy Chikurira','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Chrispen Tichaurawa",'Chrispen Tichaurawa','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Tatenda Bakure",'Tatenda Bakure','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Dr Marangwanda",'Dr Marangwanda','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Learnmore Marinyame",'Learnmore Marinyame','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Allen Hakuna",'Allen Hakuna','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Israel Mukorera",'Israel Mukorera','N/A','Misc',false);
