set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;


call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"VAWG",'VAWG','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"STI",'STI','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for HIV Self Testing",'Provider name for HIV Self Testing','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Provider Testing and Counseling",'Provider name for Provider Testing and Counseling','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Confirmatory HIV testing and Counseling",'Provider name for Confirmatory HIV testing and Counseling','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Contact Tracing",'Provider name for Contact Tracing','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Viac Initial",'Provider name for Viac Initial','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for Viac Continuation",'Provider name for Viac Continuation','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for VMMC",'Provider name for VMMC','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for FP Initial",'Provider name for FP Initial','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for FP Counselling Only",'Provider name for FP Counselling Only','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for FP Continuation",'Provider name for FP Continuation','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for VAWG",'Provider name for VAWG','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Provider name for STI",'Provider name for STI','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Stella Chabata",'Stella Chabata','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Edward Manyawu",'Edward Manyawu','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Shupikai Raini",'Shupikai Raini','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Wendy Bepe",'Wendy Bepe','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Cosmas Mbire",'Cosmas Mbire','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Gabisile Mahora",'Gabisile Mahora','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Judith Mkuli",'Judith Mkuli','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Mbekezeli Dube",'Mbekezeli Dube','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Desire Muzamhindo",'Desire Muzamhindo','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Thomas Madziro",'Thomas Madziro','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Sibusiso Macheso",'Sibusiso Macheso','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Sibonginkosi Moyo",'Sibonginkosi Moyo','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Nobukhosi Dube",'Nobukhosi Dube','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Philmon Mguni",'Philmon Mguni','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Zanele Ndlovu",'Zanele Ndlovu','N/A','Misc',false);
