set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;

call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Pregnancy Program",'Pregnancy Program','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Pregnancy Program Workflow",'Pregnancy Program Workflow','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"1st Trimester",'1st Trimester','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"2nd Trimester",'2nd Trimester','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"3rd Trimester",'3rd Trimester','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Pregnancy Program Outcomes",'Pregnancy Program Outcomes','N/A','Misc',true);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Adjust",'Adjust','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Adverse effect / event","Adverse effect / event",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Better alternative",'Better alternative','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Course Completed",'Course Completed','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Deceased",'Deceased','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Doctor's Decision","Doctor's Decision",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Dosing Problems",'Dosing Problems','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Drug not affordable",'Drug not affordable','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Drug not available",'Drug not available','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Drug to drug interaction",'Drug to drug interaction','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"End of intensive phase (TB)","End of intensive phase (TB)",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"End of Continuation phase (TB)","End of Continuation phase (TB)",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"End of induction phase (CM)","End of induction phase (CM)",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"End of consolidation phase (CM)","End of consolidation phase (CM)",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Hold / interrupt","Hold / interrupt",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Lost to follow up","Lost to follow up",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Moved to FDC",'Moved to FDC','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Patient's decision","Patient's decision",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Step up",'Step up','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Transfer out",'Transfer out','N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Treatment failure",'Treatment failure','N/A','Misc',false);