set @concept_id = 0;
set @concept_short_id = 0;
set @concept_full_id = 0;
set @count = 0;
set @uuid = NULL;

call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Facility",'Facility','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Site Type",'Site Type','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, District",'District','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Setting",'Setting','Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Service Provided",'Service Provided','N/A','Misc',true);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Gravida","Gravida",'Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Parity","Parity",'Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Observations","Observations",'N/A','Misc',true);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, TYPE OF VISIT","TYPE OF VISIT",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Wgt","Wgt",'Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, T","T",'Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, BP","BP",'N/A','ConvSet',true);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Blood Pressure Systolic Data","Systolic",'N/A','Concept Details',true);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Systolic","Systolic",'Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Systolic Abnormal","Systolic Abnormal",'Boolean','Abnormal',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Blood Pressure Diastolic Data","Diastolic",'N/A','Concept Details',true);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Diastolic","Diastolic",'Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Diastolic Abnormal","Diastolic Abnormal",'Boolean','Abnormal',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, P","P",'Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Initial (never been screened before for CaCx)","Initial (never been screened before for CaCx)",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Repeat","Repeat",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Treatment","Treatment",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Review after","Review after",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, VIAC after Positive HPV DNA Test","VIAC after Positive HPV DNA Test",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Counseling Only","Counseling Only",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Repeat Specify period","Specify period",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Treatment Specify treatment","Specify treatment",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Review after Specify details","Specify details",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, 2 Years","2 Years",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, 3 Years","3 Years",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, 4 Years","4 Years",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, 5 Years","5 Years",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, >5 Years",">5 Years",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Cryotherapy","Cryotherapy",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Thermocoagulation","Thermocoagulation",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Treatment LEEP","LEEP",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Cryotherapy","Cryotherapy",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Review after LEEP","LEEP",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Antibiotics","Antibiotics",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, HIV STATUS","HIV STATUS",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, AGE AT SEXUAL DEBUT","AGE AT SEXUAL DEBUT",'Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, NO.OF LIFETIME PARTNERS","NO.OF LIFETIME PARTNERS",'Numeric','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, PRESENTING COMPLAINTS","PRESENTING COMPLAINTS",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, PRESENTING COMPLAINTS Specify details","Specify details",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Lower Abdominal Pain","Lower Abdominal Pain",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Lower Back Pain","Lower Back Pain",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, PV Discharge","PV Discharge",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, PV Bleeding","PV Bleeding",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, PRESENTING COMPLAINTS If Other Specify details","If Other Specify details",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, EVER TREATED FOR STIS","EVER TREATED FOR STIS",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, EVER TREATED FOR STIS Specify details","Specify details",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Genital Ulcer Disease","Genital Ulcer Disease",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Vaginal Discharge Syndrome","Vaginal Discharge Syndrome",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Pelvic Inflamatory Disease","Pelvic Inflamatory Disease",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Genital Herpes","Genital Herpes",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Genital warts","Genital warts",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, EVER TREATED FOR STIS If Other Specify details","If Other Specify details",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, CONDOM USE WITH REGULAR/NON REGULAR PARTNER","CONDOM USE WITH REGULAR/NON REGULAR PARTNER",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Abstinent","Abstinent",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, PRIOR FAMILY PLANNING PREDOMINANTLY USED","PRIOR FAMILY PLANNING PREDOMINANTLY USED",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Emergency contraception","Emergency contraception",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Projesterone only pill (POP)","Projesterone only pill (POP)",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Combined oral contaceptive (COC)","Combined oral contaceptive (COC)",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Injectable (Petogen)","Injectable (Petogen)",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Implanon Implants","Implanon Implants",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Jadelle Implants","Jadelle Implants",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Copper T IUCD","Copper T IUCD",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, LNG-IUS IUCD","LNG-IUS IUCD",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Vasectomy","Vasectomy",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Tuberligation","Tuberligation",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Condoms","Condoms",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Have you ever used COC","Have you ever used COC",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, COC For how many years?","For how many years?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, less than 1","<1",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, History of smoking","History of smoking",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Smoking For how many years","For how many years",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Current Medication for Chronic conditions","Current Medication for Chronic conditions",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Chronic conditions Specify details","Specify details",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Anti-retrovirals","Anti-retrovirals",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Anti-hypertensives","Anti-hypertensives",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Diabetics","Diabetics",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Anti-Epleptics","Anti-Epleptics",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Chemotherapy","Chemotherapy",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Anti-Asthmatics","Anti-Asthmatics",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Chronic conditions If Other Specify details","If Other Specify details",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, PRIOR CA CERVIX SCREENING IN LIFETIME","PRIOR CA CERVIX SCREENING IN LIFETIME",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, When were you last screened?","When were you last screened?",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Method used in your last screen","Method used in your last screen",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, PAP SMEAR","PAP SMEAR",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, VIAC","VIAC",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, HPV DNA Testing","HPV DNA Testing",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, SCREENING METHOD USED On This Visit","SCREENING METHOD USED On This Visit",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, VIAC/ VIA","VIAC/ VIA",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, HPV DNA","HPV DNA",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Pap smear","Pap smear",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Specimen collected by","Specimen collected by",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Self-collected specimen","Self-collected specimen",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Provider-collected specimen","Provider-collected specimen",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, RESULT","RESULT",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Intervention","Intervention",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Eligible for Cryotherapy/thermocoagulation","Eligible for Cryotherapy/thermocoagulation",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Eligible for LEEP","Eligible for LEEP",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Extensive Lesion","Extensive Lesion",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Suspicious of Cancer","Suspicious of Cancer",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, OTHER PATHOLOGICAL LESIONS SEEN","OTHER PATHOLOGICAL LESIONS SEEN",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Polyps","Polyps",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Uterine Prolapse","Uterine Prolapse",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Nabothian Cysts","Nabothian Cysts",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Strawberry Lesions","Strawberry Lesions",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, PATHOLOGICAL LESIONS SEEN If Other Specify details","If Other Specify details",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Picture Files","Picture Files",'Coded','Misc',true);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Image One","Image One",'Complex','Image',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Image Two","Image Two",'Complex','Image',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Image Three","Image Three",'Complex','Image',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Image Four","Image Four",'Complex','Image',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Image Five","Image Five",'Complex','Image',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, MANAGEMENT","MANAGEMENT",'N/A','Misc',true);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, TREATMENT GIVEN","TREATMENT GIVEN",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, TREATMENT GIVEN Specify details","Specify details",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Antibiotics","Antibiotics",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Cryotherapy","Cryotherapy",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Thermocoagulation","Thermocoagulation",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, TREATMENT GIVEN LEEP","LEEP",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Client Referred","Client Referred",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Referred to","Referred to",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Public Sector","Public Sector",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, PVT sector","PVT sector",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Other NSC","Other NSC",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, referred for Public Sector","Referred for (Public Sector)",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, referred for PVT sector","Referred for (PVT sector)",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, referred for Other NSC","Referred for (Other NSC)",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Referred to Antibiotics","Antibiotics",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Referred to Cryotherapy","Cryotherapy",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Referred to Thermocoagulation","Thermocoagulation",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Referred to LEEP","LEEP",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Referred to Gynae to see","Gynae to see",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Referred for If Other Specify details","If Other Specify details (Public Sector)",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Referred for If Other Specify details PVT Sector","If Other Specify details (PVT Sector)",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Referred for If Other Specify details Other NSC","If Other Specify details (Other NSC)",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Complications/ Adverse events during procedure","Complications/ Adverse events during procedure",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Adverse events during procedure Specify details","Specify details",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Bleeding","Bleeding",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Trauma to vaginal wall","Trauma to vaginal wall",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Complications/ Adverse events during procedure , If Other Specify details","If Other Specify details",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Next appointment","Next appointment",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, REPEAT Screening","REPEAT Screening",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Repeat Screening If Other Specify details"," If Other Specify details",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, REVIEW","REVIEW",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Answer REPEAT Screening","REPEAT Screening",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, Answer REVIEW","REVIEW",'Coded','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, 6 Weeks","6 Weeks",'N/A','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form, REVIEW If Other Specify details","If Other Specify details",'Text','Misc',false);
call add_concept_psi(@concept_id,@concept_short_id,@concept_full_id,"Viac Form Template",'VIAC Form','N/A','Misc',true);